version: "3"

services:
  golang:
    image: golang
    build: ./src
    depends_on:
      - "db"

  db:
    image: db
    build: ./db
    container_name: 'db'
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
volumes:
  pgdata:
  redis: